### ISSUE TITLE
Alerts with reserved JSON strings in tags result in MicrosoftTeamsRequestException

### ISSUE THREAD

**Issue by eduardohki** [idealista/prom2teams#103]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Prometheus Alert Rules which contains JSON-restricted chars in the `descritption` and/or `summary` annotations aren't sent successfully to the Teams webhook, because the JSON body in the POST request is invalid.

Example debug log:
```
2018-12-13 11:55:00,500 - prom2teams - DEBUG - The message that will be sent is: {
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": " FF9A0B ",
    "summary": "Apache SSL Certitficate "/path/to/my/certificate.crt" is going to expire soon",
    "title": "Prometheus alarm ",
    "sections": [{
        "activityTitle": "Apache SSL Certitficate "/path/to/my/certificate.crt" is going to expire soon",
        "facts": [{
            "name": "Alarm",
            "value": "Apache_SSL_Certificate_Expiring_60d"
        },{
            "name": "In host",
            "value": "web-server"
        },{
            "name": "Severity",
            "value": "warning"
        },{
            "name": "Description",
            "value": "The Apache SSL Certitficate "/path/to/my/certificate.crt" in web-server will expire in less than 60 days"
        },{
            "name": "Status",
            "value": "firing"
        }],
           "markdown": true
    }]
}
[2018-12-13 11:55:00,518] ERROR in app: Exception on /v2/Connector [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/prom2teams/app/versions/v2/namespace.py", line 27, in post
    self.sender.send_alarms(alerts, app.config['MICROSOFT_TEAMS'][connector])
  File "/usr/local/lib/python3.6/site-packages/prom2teams/app/sender.py", line 26, in send_alarms
    post(teams_webhook_url, team_alarm)
  File "/usr/local/lib/python3.6/site-packages/prom2teams/app/teams_client.py", line 17, in post
    str(response.text)))
prom2teams.app.exceptions.MicrosoftTeamsRequestException: Error performing request to: https://outlook.office.com/webhook/XYZ/IncomingWebhook/XYZ/XYZ. Returned status code: 400. Returned data: Bad payload received by generic incoming webhook.
2018-12-13 11:55:00,518 - werkzeug - INFO - 172.17.0.1 - - [13/Dec/2018 11:55:00] "POST /v2/Connector HTTP/1.1" 500 -
```

My Prometheus Alert rule configuration:
```yml
groups:
- name: sslcert_rules
  rules:
  - alert: Apache_SSL_Certificate_Expiring_60d
    expr: round(((apache_certificate_expire_time - time()) / 60 / 60 / 24 )) < 60
    for: 5m
    labels:
      severity: warning
    annotations:
      description: The Apache SSL Certitficate "{{ $labels.certificate_path }}" in {{ $labels.instance }} will expire in less than 60 days
      summary: Apache SSL Certitficate "{{ $labels.certificate_path }}" is going to expire soon
```

### Steps to Reproduce

1. Create a test Alert Rule in Prometheus using the `"` char in the annotations text
2. Route the alert in Alertmanager to Prom2Teams endpoint
3. Force the alert trigger while checking the DEBUG logs 

**Expected behavior:** The JSON Payload sent to Teams Webhook is properly escaped when there are JSON-restricted strings

**Actual behavior:** Alerts which have JSON-restricted chars in the annotations fails while trying to be posted to the Teams Webhook

**Reproduces how often:** 100%

### Versions

Tested with v2.0.4 and v2.2.3, using the official Docker images

### Additional Information

It seems to me that the issue is somewhere between the `TemplateComposer()` and marshmallow's serialization to JSON, but I wasn't able to fix it properly in my local env. I would appreciate some help in how to address it, and thus send a PR.

**Comment by mcapra** [comment]
I was able to reproduce this on 2.3.3. Sanitized debug logs:
```
2019-06-14 13:59:22,506 - prom2teams - DEBUG - The message that will be sent is: {
...
            "name": "Description",
            "value": "Some jargon here, please search "feature:foo AND productcode:bar" on Graylog for more debugging information."
...
```

It would seem quotes in the value of the message's description aren't properly escaped in the JSON body.

**Comment by rmartinez3** [comment]
Yes issue is that if a value is sent with and quotes. It won't be escaped since the value is set as the string that is passed 

https://github.com/idealista/prom2teams/blob/master/prom2teams/teams/teams_alarm_schema.py#L9
https://github.com/idealista/prom2teams/blob/master/prom2teams/teams/teams_alarm_schema.py#L11

so then what has to be done is escape string 
instead of passing string as is
