### ISSUE TITLE
prom2teams-config.ini is not working with [Group Alerts]

### ISSUE THREAD

**Issue by Alexvianet** [idealista/prom2teams#113]
prom2teams latest version.

prom2teams-config.ini :+1: 
```
[Microsoft Teams]
# At least one connector is required here
Connector: MYURL

[HTTP Server]
Host: 0.0.0.0
Port: 8089
Name: 0.0.0.0:8089

[Group Alerts]
Field: "alertname"
```
prom2teams.stdout.log:
```
description': 'The `redis_exporter` at `10.233.171.199:9121` was unable to scrape metrics during the last 10m'}}], 'groupKey': '{}/{severity="critical"}:{alertname="RedisExporterScrapeError"}'}
2019-05-07 06:53:08,454 - flask.app - ERROR - Exception on /v2/Connector [POST]
Traceback (most recent call last):
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/prom2teams/app/versions/v2/namespace.py", line 27, in post
    self.sender.send_alarms(alerts, app.config['MICROSOFT_TEAMS'][connector])
  File "/var/vcap/packages/python/lib/python3.6/site-packages/prom2teams/app/sender.py", line 27, in send_alarms
    sending_alarms = self._create_alarms(alerts)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/prom2teams/app/sender.py", line 21, in _create_alarms
    alarms = map_and_group(alerts, self.group_alerts_by)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/prom2teams/teams/alarm_mapper.py", line 29, in map_and_group
    grouped_alerts = group_alerts(alerts[same_status_alerts], group_alerts_by)
  File "/var/vcap/packages/python/lib/python3.6/site-packages/prom2teams/teams/alarm_mapper.py", line 53, in group_alerts
    groups[alert.__dict__[group_alerts_by]].append(alert)
KeyError: '"alertname"'
```

If i add --groupalertsby "alertname" to :
exec prom2teams --configpath /var/vcap/jobs/prom2teams/config/prom2teams-config.ini \
it's works ok, troubles only with Config file.

**Comment by Alexvianet** [comment]
Same if:
[Group Alerts]
Field: alertname

  File "/var/vcap/packages/python/lib/python3.6/site-packages/prom2teams/teams/alarm_mapper.py", line 53, in group_alerts
    groups[alert.__dict__[group_alerts_by]].append(alert)
KeyError: 'alertname'

**Comment by jnogol** [comment]
It's a bit (well, way more than a bit (and a byte)) counterintuitive, but as stated [here in the readme](https://github.com/idealista/prom2teams/blob/master/README.md#usage), the field is `name` and not `alertname`. Could you please try with that?

**Comment by Alexvianet** [comment]
Omg, it works, my fail, sorry to disturb you.
Was thinking it's mapping from incoming json =)
