### ISSUE TITLE
Support for alertmanager:v0.19.0

### ISSUE THREAD

**Issue by pierrediancourt** [idealista/prom2teams#148]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Hi,

I just faced some errors in the logs of my prom2teams:latest container.
It appeared to be caused by an upgrade from prom/alertmanager:v0.18.0 to prom/alertmanager:v0.19.0
So this is not really an issue from prom2teams. 
I'm just posting to advise to take care of the additional field "fingerprint" from this new alertmanager release. 

See " [CHANGE] Add Fingerprint to template data. [#1945](https://github.com/prometheus/alertmanager/pull/1945)" 
There : https://github.com/prometheus/alertmanager/releases/tag/v0.19.0
 
Everything's just running fine with prom2teams:2.5.0 and alertmanager:v0.18.0
Close this issue as you wish :)

Thanks for you work.

### Steps to Reproduce

1. run alertmanager:v0.19.0
2. run prom2teams:2.5.0
3. docker-compose logs -f

**Reproduces how often:** 100% but not always instantaneously

### Versions

prom2teams:2.5.0

### Additional Information

 ```
prom2teams_1        | 2019-09-12 13:14:38,246 - prom2teams_app - INFO - prom2teams started on 0.0.0.0:8089
prom2teams_1        | 2019-09-12 13:14:38,247 - werkzeug - INFO -  * Running on http://0.0.0.0:8089/ (Press CTRL+C to quit)
prom2teams_1        | 2019-09-12 13:14:38,249 - werkzeug - INFO -  * Restarting with stat
prom2teams_1        | 2019-09-12 13:14:38,660 - prom2teams_app - INFO - prom2teams started on 0.0.0.0:8089
prom2teams_1        | 2019-09-12 13:14:42,946 - prom2teams - INFO - /opt/prom2teams/template.j2
prom2teams_1        | 2019-09-12 13:14:42,960 - flask.app - ERROR - Exception on /v2/Connector [POST]
prom2teams_1        | Traceback (most recent call last):
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 2292, in wsgi_app
prom2teams_1        |     response = self.full_dispatch_request()
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1815, in full_dispatch_request
prom2teams_1        |     rv = self.handle_user_exception(e)
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.12.1-py3.5.egg/flask_restplus/api.py", line 583, in error_router
prom2teams_1        |     return original_handler(e)
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.12.1-py3.5.egg/flask_restplus/api.py", line 583, in error_router
prom2teams_1        |     return original_handler(e)
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1718, in handle_user_exception
prom2teams_1        |     reraise(exc_type, exc_value, tb)
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/_compat.py", line 35, in reraise
prom2teams_1        |     raise value
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1813, in full_dispatch_request
prom2teams_1        |     rv = self.dispatch_request()
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1799, in dispatch_request
prom2teams_1        |     return self.view_functions[rule.endpoint](**req.view_args)
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.12.1-py3.5.egg/flask_restplus/api.py", line 325, in wrapper
prom2teams_1        |     resp = resource(*args, **kwargs)
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/views.py", line 88, in view
prom2teams_1        |     return self.dispatch_request(*args, **kwargs)
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.12.1-py3.5.egg/flask_restplus/resource.py", line 44, in dispatch_request
prom2teams_1        |     resp = meth(*args, **kwargs)
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/prom2teams-2.5.0-py3.5.egg/prom2teams/app/versions/v2/namespace.py", line 26, in post
prom2teams_1        |     alerts = self.schema.load(request.get_json())
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/marshmallow-3.0.0rc6-py3.5.egg/marshmallow/schema.py", line 707, in load
prom2teams_1        |     postprocess=True,
prom2teams_1        |   File "/usr/local/lib/python3.5/site-packages/marshmallow-3.0.0rc6-py3.5.egg/marshmallow/schema.py", line 867, in _do_load
prom2teams_1        |     raise exc
prom2teams_1        | marshmallow.exceptions.ValidationError: {'alerts': {0: {'fingerprint': ['Unknown field.']}, 1: {'fingerprint': ['Unknown field.']}}}
prom2teams_1        | 2019-09-12 13:14:42,961 - prom2teams_app - ERROR - An unhandled exception occurred. {'alerts': {0: {'fingerprint': ['Unknown field.']}, 1: {'fingerprint': ['Unknown field.']}}}
```

**Comment by miguel-chacon** [comment]
Hi @pierrediancourt 

Take a look on 2.5.1 version

Thanks,
