### ISSUE TITLE
alertmanager 0.21 - flask.app - ERROR - Exception on / [POST]

### ISSUE THREAD

**Issue by jcmartins** [idealista/prom2teams#194]
**alertmanager --version**
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4

**docker images**
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
idealista/prom2teams       2.5.6               85a32f6a1d8d        10 days ago         250MB

**docker logs** 7bb 
2020-07-23 16:21:51,231 - prom2teams_app - INFO - prom2teams started on 0.0.0.0:8089
2020-07-23 16:21:51,231 - werkzeug - INFO -  * Running on http://0.0.0.0:8089/ (Press CTRL+C to quit)
2020-07-23 16:21:51,232 - werkzeug - INFO -  * Restarting with stat
2020-07-23 16:21:51,539 - prom2teams_app - INFO - prom2teams started on 0.0.0.0:8089
2020-07-23 16:21:51,541 - prom2teams - INFO - /usr/local/lib/python3.5/site-packages/prom2teams/resources/templates/teams.j2
2020-07-23 16:21:51,561 - flask.app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v1/namespace.py", line 29, in post
    alerts = self.schema.load(request.get_json())
  File "/usr/local/lib/python3.5/site-packages/marshmallow/schema.py", line 707, in load
    postprocess=True,
  File "/usr/local/lib/python3.5/site-packages/marshmallow/schema.py", line 867, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'truncatedAlerts': ['Unknown field.']}
2020-07-23 16:21:51,563 - prom2teams_app - ERROR - An unhandled exception occurred. {'truncatedAlerts': ['Unknown field.']}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v1/namespace.py", line 29, in post
    alerts = self.schema.load(request.get_json())
  File "/usr/local/lib/python3.5/site-packages/marshmallow/schema.py", line 707, in load
    postprocess=True,
  File "/usr/local/lib/python3.5/site-packages/marshmallow/schema.py", line 867, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'truncatedAlerts': ['Unknown field.']}
2020-07-23 16:21:51,574 - werkzeug - INFO - 172.17.0.1 - - [23/Jul/2020 16:21:51] "POST / HTTP/1.1" 500 -
2020-07-23 16:21:51,584 - werkzeug - ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v1/namespace.py", line 29, in post
    alerts = self.schema.load(request.get_json())
  File "/usr/local/lib/python3.5/site-packages/marshmallow/schema.py", line 707, in load
    postprocess=True,
  File "/usr/local/lib/python3.5/site-packages/marshmallow/schema.py", line 867, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'truncatedAlerts': ['Unknown field.']}

**Comment by dortegau** [comment]
Fixed in https://github.com/idealista/prom2teams/issues/210
