### ISSUE TITLE
Getting 405 Status when Trying API v2, Notifications to Teams are not triggering

### ISSUE THREAD

**Issue by jayraviteja** [idealista/prom2teams#199]
### Description

Hello All,

I have installed the prom2teams latest version i.e 2.5.6 with Python-3.6.9 in an VM(IP:- xx.xx.xx.xx).

Below is my Alertmanager Configuration.

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'msteams'
receivers:
  - name: 'msteams'
    webhook_configs:
      - url: 'http://prom2teams-ip:8089/v2/'

Below is the Log Showing in Prom2Teams console and Notifications are Not triggering.

![image](https://user-images.githubusercontent.com/38829329/89012437-dcd39980-d32f-11ea-8111-272e2f853464.png)

Please let me know where I am doing wrong..

Also pls let me know if any configuration needs to be done in prometheus as well(other than alertmanager.yaml)?

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]
Notifications to Teams channel should be Triggered

**Actual behavior:** [What actually happens]
Below are the two URLs when calling from Alertmanager.
1) Showing 405 Error with xx.xx.xx.xx:8089/v2/.
2) Showing the below Validation Error with xx.xx.xx.xx:8089/ 

2020-07-31 07:31:08,854 - prom2teams_app - ERROR - An unhandled exception occurred. {'alerts': {0: {'startsAt': ['Not a valid datetime.'], 'endsAt': ['Not a valid datetime.']}}}
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/prom2teams/app/versions/v1/namespace.py", line 29, in post
    alerts = self.schema.load(request.get_json())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/marshmallow/schema.py", line 707, in load
    postprocess=True,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/marshmallow/schema.py", line 867, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'alerts': {0: {'startsAt': ['Not a valid datetime.'], 'endsAt': ['Not a valid datetime.']}}}

Also I have configured the config.ini correctly in the VM Where this prom2teams is configured and passed the Microsoft Teams Connector correctly and the connector also working fine.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Prometheus:- 2.14.0
Alertmanager:- 0.19.0
Python:- 3.6.9
Pip:- 9.0.1
prom2teams:- 2.5.6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mogoman** [comment]
Hi

Your webhook url appears to be wrong. You need to call http://prom2teams-ip:8089/v2/<connector name> (example http://prom2teams-ip:8089/v2/Connector if you are using ENV vars in Docker)

**Comment by srl295** [comment]
> Hi
> 
> Your webhook url appears to be wrong. You need to call http://prom2teams-ip:8089/v2/ (example http://prom2teams-ip:8089/v2/Connector if you are using ENV vars in Docker)

Not clear, see #274 — I get an error using `http://prom2teams-ip:8089/v2/Connector` similar to above (invalid datetime)
