### ISSUE TITLE
Error at app start

### ISSUE THREAD

**Issue by zamir0109** [idealista/prom2teams#206]
Hi, just want to notify this

### Description

When using Docker, the service starts correctly, however when an alert is sent the following exception is thrown
```

2020-08-13 16:42:18File "/usr/local/lib/python3.5/site-packages/prom2teams/app/versions/v2/namespace.py", line 18, in __init__
2020-08-13 16:42:18self.schema = MessageSchema(exclude_fields=app.config['LABELS_EXCLUDED'], exclude_annotations=app.config['ANNOTATIONS_EXCLUDED'], unknown=EXCLUDE)
self.schema = MessageSchema(exclude_fields=app.config['LABELS_EXCLUDED'], exclude_annotations=app.config['ANNOTATIONS_EXCLUDED'], unknown=EXCLUDE)
2020-08-13 16:42:18TypeError: __init__() got an unexpected keyword argument 'unknown'
TypeError: __init__() got an unexpected keyword argument 'unknown'
2020-08-13 16:42:182020-08-13 21:42:18,267 - prom2teams_app - ERROR - An unhandled exception occurred. __init__() got an unexpected keyword argument 'unknown'
2020-08-13 21:42:18,267 - prom2teams_app - ERROR - An unhandled exception occurred. __init__() got an unexpected keyword argument 'unknown'
2020-08-13 16:42:18Traceback (most recent call last):
Traceback (most recent call last):
2020-08-13 16:42:18File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
```

### Steps to Reproduce

1. Map volume with config.ini file, several or single connector, it doesn't matter
2. Alertmanager points to the container with "localhost:9096/v2/foo"
3. The config.ini file is configured with port 9096

**Expected behavior:** App receives alerts

**Actual behavior:** When receiving an alert, an exception is thrown

**Reproduces how often:** Always

### Versions

DOCKER CONTAINER v2.5.7

**Comment by mafr** [comment]
Same issue here, reproducible in v2.5.8, too.
