### ISSUE TITLE
[BUG] does not handle precise date/

### ISSUE THREAD

**Issue by srl295** [idealista/prom2teams#276]
### Description

Precise date/time not handled, validation err with the following

```json
            "startsAt": "2021-08-20T20:37:20.544831675Z",
            "endsAt": "2021-08-20T20:57:35.544831675Z",
```

### Steps to Reproduce

1. Set up prom2teams

**Expected behavior:**
alerts

**Actual behavior:**
validation errs

**Reproduces how often:** 
100%

### Environment

- Ubuntu 20.04.1 LTS (Focal Fossa) 
- Linux ss 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Snaps:
```
Name                        Version  Rev  Tracking       Publisher   Notes
prometheus                  2.20.1   32   2/stable       canonical✓  -
prometheus-alertmanager-is  0.21.0   1    latest/stable  alejdg      -
```

**Comment by srl295** [comment]
```
2021-08-20 16:04:07,811 - prom2teams_app - ERROR - An unhandled exception occurred. {'alerts': {0: {'endsAt': ['Not a valid datetime.'], 'startsAt': ['Not a valid datetime.']}}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/prom2teams/app/versions/v2/namespace.py", line 26, in post
    alerts = self.schema.load(request.get_json())
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 706, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/dist-packages/marshmallow/schema.py", line 868, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'alerts': {0: {'endsAt': ['Not a valid datetime.'], 'startsAt': ['Not a valid datetime.']}}}
```
