### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jaheimxu** [idealista/prom2teams#357]
an error:

configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=4-cksFBPsWepXWj7Dul6uHImdZM1lSz8dW-tHXE1xKg'
2024-11-26 03:46:12,292 - prom2teams_app - ERROR - An unhandled exception occurred. '%' must be followed by '%' or '(', found: '%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=4-cksFBPsWepXWj7Dul6uHImdZM1lSz8dW-tHXE1xKg'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restplus/api.py", line 583, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prom2teams/app/versions/v2/namespace.py", line 27, in post
    self.sender.send_alerts(alerts, app.config['MICROSOFT_TEAMS'][connector])
  File "/usr/local/lib/python3.8/configparser.py", line 1255, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/local/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/local/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/local/lib/python3.8/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=4-cksFBPsWepXWj7Dul6uHImdZM1lSz8dW-tHXE1xKg'
[pid: 13|app: 0|req: 59/59] 10.115.104.84 () {26 vars in 354 bytes} [Tue Nov 26 03:46:12 2024] POST /v2/Connector => generated 126 bytes in 6 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)

**Comment by jverger** [comment]
I had the same error, to fix it, **as workaround**, i have doubled the '%' (percent) character as explained in the error message:
`configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=4-cksFBPsWepXWj7Dul6uHImdZM1lSz8dW-tHXE1xKg'`
e.g:
`%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=4-cksFBPsWepXWj7Dul6uHImdZM1lSz8dW-tHXE1xKg`
becomes:
`%%2Ftriggers%%2Fmanual%%2Frun&sv=1.0&sig=4-cksFBPsWepXWj7Dul6uHImdZM1lSz8dW-tHXE1xKg`
