### ISSUE TITLE
Version 2.20 does not work

### ISSUE THREAD

**Issue by wsz87** [idealista/prom2teams#90]
### Description
Version 2.2.0 neither works installed through pip nor inside Docker image.

### Steps to Reproduce

For the three problems:
Every check was done just by sending a message stored in 
https://github.com/idealista/prom2teams/blob/master/tests/data/jsons/all_ok.json to POST /v2/Connector

1) Docker image (installed version is 2.1.2)
2) Installed through PIP fails for two reasons:
 
     - typo in AlertReceiver -> app.config('GROUP_ALERTS') instead of app.config['GROUP_ALERTS_BY']
     - once typo is fixed message cannot be sent to any Teams channel. Due to lack of adapters in config.
   
     The same config worked for Docker Image 2.2.1. The config is enclosed.

**Expected behavior:**
To send notifications.

**Actual behavior:**
Exception: requests.exceptions.InvalidSchema: No connection adapters were found for '<Section: Microsoft Teams>'. See the attached log file for the stack.

**Reproduces how often:** 
100 % of calls

### Version
2.2.0

Config and logs: [prom2teams.zip](https://github.com/idealista/prom2teams/files/2371595/prom2teams.zip)

**Comment by jnogol** [comment]
Hi @wsz87,

Yes, looks like v2.2.0 it's a buggy version. We're taking a look on it. Stay tuned and thank you for your feedback.

**Comment by jnogol** [comment]
Hi again @wsz87,

We've just released v2.2.1. Please let us know if the bug is still present.

**Comment by wsz87** [comment]
I'm still having issues while testing (with a direct call to POST /v2/Connector using payload from https://raw.githubusercontent.com/idealista/prom2teams/master/tests/data/jsons/all_ok.json) and regular notifications from Alert Manager. I'm using the newest Docker image image with 2.2.1 tag:

```
2018-09-14 08:02:21,961 - prom2teams - DEBUG - JSON received is:
{'alerts': [{'endsAt': datetime.date(2017, 5, 9), 'startsAt': datetime.date(2017, 5, 9), 'generatorURL': 'my.prometheusserver.url', 'status': 'resolved', 'labels': {'alertname': 'DiskSpace', 'mountpoint': '/', 'severity': 'severe', 'instance': 'cs30.evilcorp', 'job': 'fsociety', 'device': 'rootfs', 'fstype': 'rootfs'}, 'annotations': {'description': 'disk usage 93% on rootfs device', 'summary': 'Disk usage alert on CS30.evilcorp'}}], 'externalURL': 'my.prometheusalertmanager.url', 'version': '4', 'status': 'resolved', 'receiver': 'test_webhook'}
2018-09-14 08:02:21,962 - prom2teams - DEBUG - The message that will be sent is: {
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": " 2DC72D ",
    "summary": "(Resolved) Disk usage alert on CS30.evilcorp",
    "title": "Prometheus alarm (Resolved) ",
    "sections": [{
        "activityTitle": "Disk usage alert on CS30.evilcorp",
        "facts": [{
            "name": "Alarm",<F12>
            "value": "DiskSpace"
        },{
            "name": "Target",
            "value": "cs30.evilcorp"
        },{
            "name": "Severity",
            "value": "severe"
        },{
            "name": "Description",
            "value": "disk usage 93% on rootfs device"
        },{
            "name": "Status",
            "value": "resolved"
        }],
           "markdown": true
    }]
}
2018-09-14 08:02:22,018 - flask.app - ERROR - Exception on /v2/Connector [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.10.1-py3.5.egg/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.10.1-py3.5.egg/flask_restplus/api.py", line 557, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.10.1-py3.5.egg/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/Flask-1.0.2-py3.5.egg/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restplus-0.10.1-py3.5.egg/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/prom2teams-2.2.1-py3.5.egg/prom2teams/app/versions/v2/namespace.py", line 27, in post
    self.sender.send_alarms(alerts, app.config['MICROSOFT_TEAMS'][connector])
  File "/usr/local/lib/python3.5/site-packages/prom2teams-2.2.1-py3.5.egg/prom2teams/app/sender.py", line 30, in send_alarms
    post(teams_webhook_url, team_alarm)
  File "/usr/local/lib/python3.5/site-packages/prom2teams-2.2.1-py3.5.egg/prom2teams/app/teams_client.py", line 17, in post
    str(response.text)))
prom2teams.app.exceptions.MicrosoftTeamsRequestException: Error performing request to: https://outlook.office.com/webhook/[..]. Returned status code: 400. Returned data: Bad payload received by generic incoming webhook.
2018-09-14 08:02:22,020 - werkzeug - INFO - 172.18.0.3 - - [14/Sep/2018 08:02:22] "POST /v2/Connector HTTP/1.0" 500 -
```

**Comment by jnogol** [comment]
Mmm, that's odd. Just tried and works smoothly. Try this:

```bash
docker pull idealista/prom2teams:2.2.1
docker run -d -it -e PROM2TEAMS_LOGLEVEL="DEBUG" -e PROM2TEAMS_GROUP_ALERTS_BY=name -e PROM2TEAMS_CONNECTOR=YOUR_CONNECTOR -p 8089:8089 --name prom2teams idealista/prom2teams:2.2.1
```

And then:

```bash
cd tests/data/jsons/
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d @all_ok.json 'http://localhost:8089/v2/Connector'
```

This gives me an OK and the alerts perfectly sent to MS Teams.

**Comment by wsz87** [comment]
Have you checked without env variable PROM2TEAMS_GROUP_ALERTS_BY=name ?

**Comment by wsz87** [comment]
You're right the error was with my custom template that I added yesterday. Everything works fine. Thank you for outstanding support.

**Comment by jnogol** [comment]
No problem at all, thank you for your feedback. Shall we close the issue then?

**Comment by wsz87** [comment]
I think we can close it. Despite of that I see one useful change. It is always to group by status, give an option to specify a list of fields to group by or just give a different color per target.

On the below picture we can see that we have one message for fired and resolved messages:
![image](https://user-images.githubusercontent.com/16073158/45551969-b1c12900-b82f-11e8-9621-e0f64cebceba.png)

The problem without grouping by status that we don't see on the first sight which ones are resolved and which don't. Similarly, the same problem exist for different severities. I've tried to modify Jinja/Teams transformation, but I think it is not doable without modifying the code.

**Comment by jnogol** [comment]
Hi @wsz87,

We're working on the next version and it'll group by status in any case, as we find this scenario the most sensible one.

Regards,
Jose

**Comment by wsz87** [comment]
Really good to hear it. I've also tested the version and it works perfectly. Thx.
